
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param montantEuro
     * @return
     *     returns double
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertToDH", targetNamespace = "http://ws/", className = "proxy.ConvertToDH")
    @ResponseWrapper(localName = "convertToDHResponse", targetNamespace = "http://ws/", className = "proxy.ConvertToDHResponse")
    @Action(input = "http://ws/BanqueWS/convertToDHRequest", output = "http://ws/BanqueWS/convertToDHResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ws/BanqueWS/convertToDH/Fault/Exception")
    })
    public double convertToDH(
        @WebParam(name = "montantEuro", targetNamespace = "")
        double montantEuro)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://ws/", className = "proxy.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://ws/", className = "proxy.GetComptesResponse")
    @Action(input = "http://ws/BanqueWS/getComptesRequest", output = "http://ws/BanqueWS/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws/", className = "proxy.GetCompteResponse")
    @Action(input = "http://ws/BanqueWS/getCompteRequest", output = "http://ws/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
